spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    #username: ${MAIL_USER_NAME}
    #password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  h2:
    console:
      enabled: true

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      springframework:
        security: TRACE

jwt:
  secret: VTNCeWFXNW5JRk5sWTNWeWFYUjVJRWR2YkdSbGJpQlVhV05yWlhR
  grant-type: Bearer
  token-validate-in-seconds: 3600

yanolja:
  url:
    base: http://localhost:8080
    reservations: /dummy/reservations/{yaUserId}
    reservation: /dummy/reservation/{reservationId}
